sudo: false
language: java
script: "./gradlew publish"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: releases
  api_key:
    secure: QKq/CE+Tf2LwFC7kqlMVh9lyJ48IUYpPeQIyq6bIs/GpFzIfOnvcXxuKetVH/Eg0ohSAnasb8+eC0jqkVQH2fHiEE/vb4QsoLsxfPURvYrmq1tXeM9FYqi7xPFFCEHOkAy8pKkFJydGduJQWIUH0ibVm8/nYyLr6OZPhPdLnWv4=
  file: build/lib/rat-xml-1.0.0.jar
  skip_cleanup: true
  on:
    repo: duckAsteroid/sg-cdb
    tags: true
env:
  global:
  - secure: FZYs+xjMo9o0nX96NPE+9DbvrP0nVCCtyG9fqwYx3FO99Oe6PymJOfJxUlIhA+sJGerFFhJ4pP38xV1SR0i0h1GY+gsZKtfnmPjB8CtIDjMeTN0iV38Fn+7Ydghkx4ylTI6yfmticdvuCQSyQMad5BoD4Wp2Kan0T2H1uGR8zk0VonnsuQuxlYkO8NekDV4CQi00ErB2tja02fJZBqU0ErghlVCh8qDnkTBNbWHbvN/BKrarZECSTsWqUzoA6nGKA8WSn1j3fpV0ZnKc8jEexYD7SCxP642DZsHbl1TGa2KnSj5XcUb/RDVuFwtTXsj7PPbywjlFOQhOdEV4dh9ELONE4QS54Yk8OHazhGOUyiCL0aRuZDcVoJ1DD1b/FaNty+ZgVaY02B2ObpHCEhq5bnt94VPHzsZjxyWAWamSxX3XoDjahsCkjOtgqoZMAamXF6rhp01R4EJd/MWHJD2xhBkdPKD6QDSZ4/DEn4Rv1bcZHm3x+XpR6eVSD18oFiycRgKbPyXlvBOHp3Q7PE92QVR/Yaowm7YGC7duJjFTH/ILr26XvwGD0wptTRn7nVaU68YFWO2wvTHcinTo53a0ps288vKKoZHdbaEW2wcbGfnhWGYicJzTSkd7MRKsVDWQDHMft6pCi1yIVobxK8wYjWDU7jmjCYxE7lizTXXw7V4=
  - secure: Tfry5UpvEVKLgaI2ALbGFqrYQfy7w4ffNnhH2FCTR8a0Wr7SnEAtbf5yUtecqVSjd+Kf1X8XENBH8dKLQslRvbC1QkxLwrHFo9YzpPnfD35+dmP3/KC7LMiR0iY12Y9eY8XdYyWEQv3ozxk1+OFr3rhsVLbJauYOuRTTx/wXHte52BMgjGV+77P0r4IHzZZL5WuwzE319XLDB6CR5eSjDKup3dLEQ+vGtLQQrAf4YoXtmuIVA6p+KL9quK17psiwvcenDSUWY6QB+XqKThfvZv+EHRkGJFCmgGNMHpDbPEIr6qLRxPgR3wGPKMLgBNA1Nkl8z8g5GyjjH09zW3lyKmLs/nVDIC3Jq6S+WtyJGrsaxVpTr6FTTuumDLAHj0uqIbLlJuPyC5ky0JQDzUKcndoKzvRhcXtEStY6Pv3qToeclIkAmhW6xLE8AH79yM6GrCLUb27GJ4b/enXTfP+A+E8B+RB+aY3cBMrtpL0NasOIldRVW1XJ8Eci+/4j/dgSh8pbuZ3PuL+3lIY8NSz8TrN8aACkpx9j8lm+k36Tf/p/FK3pg1vLbYWpVMTieJrC3aUcKNMqyAdL/dI9pYjOeV+WkauYMHRCts6kFGUHB7xLQ0R2ThxP6jbt3cEYmTZN529beB3+OEfaLTcmITH0K13UPyG8MoHLnqG63dc1zjc=
  - secure: IR9SBYF9Jgtd5T6z0cKFILUBXbDkCAR08FBNqkzsKtyScgKLVKeuAdy/MJdzkz18j4q7xHBxp13YIDaE7nbNFx4m3be9iMeANRYbfqdjT2lfRSosesV5H8xXAIW0d5n5EaXy/BRhNZQDfcg1BUPScChQCPNuCB8Kopvlmagj32CJpDMq5Txc/2ZUOKf+QsciyU3mKEVzfRbJpUNNR4pZpLp9bl4SE5sE1mwkVQdBsmym7xSbPex4/rZTauS8sJdsWAu7L6YRIzggRwnMWeheax8VhsuY8CiUfeAuP9EqlRsBBwUXn9/xoM1GnFNcBVWmXdLxy9PWW4/KroclwumeBoChHTYb+LvILgNXpXp6UcQj2XSCSEybGZVH7AbaZDV13aW5lF2ZMTagaWysfYg7FZ936IkHELYyyiILnLaHrR7ZCWJc0aSOosFOYYFMkS7Z+D1Iur/zy0RA+XBdNJeeLk9LvnZeQiUXUOsuMFXCDc9WUVaKvPm2niv9ylmd3MN5JXa+eywYKfyv4LgUKFFKKng7ODyi+U/1JnoAfbAWTZfMWBfhB3aJF7TCxYPYNlw+dP+Df/hPt/BMrHdhQ3+455p9EHIxnBJjS3UUUv3w2RxfCXZ+s0e2/vwVaImzMtDrNx0ByCO1fL0dVkV3qxKPeJdWFyN41rbjNiU/iY8irkA=
